name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'
          chanel: stable
          cache: true
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Lint
        run: |
          flutter format --set-exit-if-changed --dry-run .
          flutter analyze
